kafka:
  bootstrap-servers: localhost:9092
  security:
    # protocol: SSL or SASL_SSL
    protocol: SSL
    # Truststore (if using custom certs)
    ssl-truststore-location: "/path/to/truststore.jks"
    ssl-truststore-password: "changeit"
    ssl-truststore-type: "JKS"
    # Keystore (if mutual TLS is required)
    ssl-keystore-location: "/path/to/keystore.jks"
    ssl-keystore-password: "changeit"
    ssl-keystore-type: "JKS"
    ssl-key-password: "changeit"
    # Disable hostname verification if needed (not recommended for prod)
    ssl-endpoint-identification-algorithm: "HTTPS"
    # For SASL (uncomment if using SASL_SSL)
    # sasl-mechanism: PLAIN
    # sasl-jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="pass";
  topics:
    orders:
      topic-name: orders.v1
      group-id: orders-consumer-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      concurrency: 1
      poll-timeout: 3s
      handler-bean: ordersHandler
      properties:
        max.poll.records: "100"
      start:
        timestamp-ms: 1719427200000
    payments:
      topic-name: payments.v1
      group-id: payments-consumer-group
      enable-auto-commit: false
      auto-offset-reset: latest
      concurrency: 1
      poll-timeout: 3s
      handler-bean: paymentsHandler
      properties:
        max.poll.records: "100"
      start:
        partition-to-offset:
          "0": 123
          "1": 456

logging:
  level:
    root: INFO
    com.example.dynamickafkaconsumers: DEBUG

