kafka:
  bootstrap-servers: localhost:9092
  topics:
    orders:
      topic-name: orders.v1
      group-id: orders-consumer-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      concurrency: 1
      poll-timeout: 3s
      handler-bean: ordersHandler
      properties:
        max.poll.records: "100"
      start:
        timestamp-ms: 1719427200000
    payments:
      topic-name: payments.v1
      group-id: payments-consumer-group
      enable-auto-commit: false
      auto-offset-reset: latest
      concurrency: 1
      poll-timeout: 3s
      handler-bean: paymentsHandler
      properties:
        max.poll.records: "100"
      start:
        partition-to-offset:
          "0": 123
          "1": 456

logging:
  level:
    root: INFO
    com.example.dynamickafkaconsumers: DEBUG

